---
title: "Stat_Hw3"
author: "Ellie Suit, Andy Atallah, and Ai Hattori"
date: "2023-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(sf)
library(tidyverse)
library(rattle)
library(rpart)

stop_data <- stop_data %>%
  mutate(time = as_datetime(responseDate),
         year = year(time),
         month = month(time),
         day = day(time),
         race = factor(race),
         gender = factor(gender),
         preRace = factor(preRace),
         policePrecinct = factor(policePrecinct),
         problem = factor(problem)) 

gf_date <- as.Date("2020-05-25")
stop_data <- stop_data %>%
  mutate(case = case_when(time <= gf_date ~ 0,
                          time > gf_date ~ 1))

before_gf <- stop_data %>%
  filter(case == 0) 
after_gf <- stop_data %>%
  filter(case == 1) %>%
  mutate(race = factor(race),
  gender = factor(gender),
  preRace = factor(preRace),
  policePrecinct = factor(policePrecinct),
  problem = factor(problem)) 
tree <- rpart(problem ~ race + gender + preRace, data = before_gf)
fancyRpartPlot(tree)


rf <- randomForest(problem ~ race + gender + preRace + policePrecinct, 
                   data = before_gf %>% na.omit(),
                   importance = TRUE)
rf2 <- randomForest(problem ~ gender, 
                   data = after_gf %>% na.omit())

view(rf$importance)

```
```{r}
table(after_gf$gender)
```


